name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  merge_group:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_pre_commit:
    name: Check - pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82

      - name: Check pre-commit hook
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  check_pyright:
    name: Check - pyright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82

      - name: Check - pyright
        run: uv run pyright .

  run_python_tests:
    name: Run tests (Python)
    needs: [check_pre_commit, check_pyright]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout source code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82

      - name: Run pytest
        run: uv run pytest -vvv
